kakao:
  key: "KakaoAK 7e1c3d53c917a4450aeff99691f0690f"
  host: "http://localhost:8082"
  end-points:
    blog-list-uri: "/v2/search/blog"

kakao-mock:
  port: 8082
  end-points:
    blog-list-uri: "/v2/search/blog"


