spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/blogdb;AUTO_SERVER=true
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:

        dialect: org.hibernate.dialect.H2Dialect
        #하이버네이트가 실행하는 모든 SQL문을 콘솔로 출력해 준다.
        show_sql: true
#        #콘솔에 출력되는 JPA 실행 쿼리를 가독성있게 표현한다.
#        format_sql: true
#        #디버깅이 용이하도록 SQL문 이외에 추가적인 정보를 출력해 준다.
#        use_sql_comments: true

    generate-ddl: true
    open-in-view: false